spring:

  datasource:
    url: jdbc:postgresql://13.124.236.229:5432/cdbd_db
    username: cdbd
    password: Pa$$w0rd
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

    
  # Swagger
  springdoc:
    version: '@springdoc.version@'
    swagger-ui:
      display-request-duration: true
      groups-order: DESC
      operationsSorter: method
      disable-swagger-default-url: true
      use-root-path: true
    show-actuator: true
    group-configs:
      - group: stores
        paths-to-match: /swagger/**
                                                          
# Server Port
server:
  port: 9999